name: Five
favicon: null
layout_spectrum: 0.1542764655314386
typography_spectrum: 0.6362022913526744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.26709998515434563
  lightness: 0.9024800851475447
  saturation: 0.664195109391585
  rhythmicContrast: 0.7689466725569218
purpose: []
