name: Five
favicon: null
layout_spectrum: 0.93558
typography_spectrum: 0.53937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9efbd'
    - '#206c77'
    - '#8a8a8a'
    - '#ad0505'
  brandStrength: 0.75
  lightness: 0.9024800851475447
  saturation: 0.664195109391585
  rhythmicContrast: 0.7689466725569218
purpose: []
